name: mouse
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"
resolution: workspace

flutter:
  plugin:
    platforms:
      macos:
        default_package: mouse_macos
      windows:
        default_package: mouse_windows
      # TODO: Implement other platforms following same example (url_launcher)

dependencies:
  flutter:
    sdk: flutter
    
  mouse_platform_interface:
    path: ../mouse_platform_interface

  mouse_macos:
    path: ../mouse_macos
  
  mouse_windows:
    path: ../mouse_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
